version: '3.8'

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Wilder26?
      MYSQL_DATABASE: control_pacientes
      MYSQL_USER: root
      MYSQL_PASSWORD: Wilder26?
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

 
volumes:
  mysql-data:
    driver: local

