server:
  port: 8081
  servlet:
    context-path: /crp
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/crp-bd
      username: microjava
      password: javajava
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
